commerce_payment.commerce_payment_gateway.plugin.gercpay:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    secret_key:
      type: string
      label: 'Secret Key'
    language:
      type: string
      label: 'language'
